version: '3.8'
services:
  database:
    image: tzuhsuannn/mysqlshop
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: "passwd"
    ports:
      - "8306:3306"
    volumes:
      - simpleshop:/var/lib/mysql
     # - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
     # - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      backend:
        aliases:
          - "database"
  myapp:
    image: tzuhsuannn/simpleshopmysql:0.0.1-SNAPSHOT
    container_name: simpleshopapp
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://database:3306/simpleshop"
      SPRING_DATASOURCE_PASSWORD: "passwd"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend
volumes:
  simpleshop:
networks:
  backend:
    driver: bridge