name: Docker Image CI/CD
on:
  push:
    branches: [ master ]
jobs:
  # 构建并上传 Docker镜像
  build:
    runs-on: ubuntu-latest # 依赖的环境
    steps:
      - uses: actions/checkout@v3
      - name: Build Image
        run: |
          cd docker
          docker build -t tzuhsuannn/mysqlshop .
          cd ..
          mvn clean package dockerfile:build -DskipTests=true
      - name: Login to Registry
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Image
        run: |
          docker push tzuhsuannn/mysqlshop
          docker push tzuhsuannn/simpleshopmysql:0.0.1-SNAPSHOT


  deploy-docker:
    needs: [ build ]
    name: Deploy Docker
    runs-on: ubuntu-latest
    steps:
      - name: Get repository metadata
        uses: varunsridharan/action-repository-meta@main
        env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }} # 服务器登录密码
          # port: 8088
          script: |
            echo '啟用 Laravel 內建的維護模式's
            docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} 
            docker-compose -f docker-compose.yml up