name: Docker Image CI/CD
on:
  push:
    branches: [ master ]
jobs:
  # 构建并上传 Docker镜像
  build:
    runs-on: ubuntu-latest # 依赖的环境
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Build Image
        run: |
          cd docker
          docker build -t tzuhsuannn/mysqlshop .
          cd ..
          mvn clean package dockerfile:build -DskipTests=true
      - name: Login to Registry
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Image
        run: |
          docker push tzuhsuannn/mysqlshop
          docker push tzuhsuannn/simpleshopmysql:0.0.1-SNAPSHOT



  deploy-docker:
    needs: [ build ]
    name: Deploy Docker
    runs-on: ubuntu-latest
    steps:
      - name: Get repository metadata
        uses: varunsridharan/action-repository-meta@main
        env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          SOURCE: simpleshopmysql/
          TARGET: /Users/tzuhsuan/Downloads/
          script: |
            # 切换工作区
            cd docker
            # 登录镜像服务器
            docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} 
            # 创建并启动容器
            docker-compose -f docker-compose.yml up